
server:
  port: 8080
  servlet:
    contextPath: /mssivimss-servicios-externos/v1
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cache:
    redis:
      time-to-live: 30000
      
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: ${msit_CONNECTION_DB}
    username: ${msit_CONNECTION_DB}
    password: ${msit_CONNECTION_DB}
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: 1
      
      
  main:
    allow-circular-references: true
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
   sat: ${msit_CONNECTION_DB}
   sepomex: ${msit_CONNECTION_DB}
   renapo: ${msit_CONNECTION_DB}
   siap: ${msit_CONNECTION_DB}
   correo: ${msit_CONNECTION_DB}

jwt:
  login: ${msit_CONNECTION_DB}
  secretkey-flujo: ${msit_CONNECTION_DB}
  expiration-milliseconds: 360

management:
      endpoints:
          web:
            exposure:
                include:
                    health,info,metrics

resilience4j.circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      msflujo:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: ${msit_HILOS}
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: ${msit_TIEMPO_DURACION}
        permittedNumberOfCallsInHalfOpenState: ${msit_NUMERO_INTENTOS}
        slidingWindowSize: '5'
resilience4j.retry:
    retryAspectOrder: 2
    instances:
        msflujo:
           maxAttempts: ${msit_NUMERO_INTENTOS}
           waitDuration: ${msit_TIEMPO_DURACION}
resilience4j.timelimiter:
    timeLimiterAspectOrder: 3
    instances:
      msflujo:
        timeout-duration: ${msit_TIEMPO_DURACION}
        
correo:
  remitente: ${msit_REMITENTE}

ruta-log: ${msit_RUTA_LOG}
