
server:
  port: 8083
  servlet:
    contextPath: /mssivimss-servicios-externos/v1
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cache:
    redis:
      time-to-live: 30000
      
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/SVBDQA
    username: pmsoluciones
    password: Tr1357.*
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: 1
      
      
  main:
    allow-circular-references: true
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
   sat: "http://serviciosdigitalesinterno-stage.imss.gob.mx/serviciosDigitales-rest/v1/externos/sat/rfc"
   sepomex: "http://serviciosdigitalesinterno-stage.imss.gob.mx/serviciosDigitales-rest/v1/domicilios/asentamientos/codigoPostal"
   renapo: "http://serviciosdigitalesinterno-stage.imss.gob.mx/serviciosDigitales-rest/v1/externos/renapo/curp"
  
jwt:
  login: funcionamuybienlogin
  secretkey-flujo: funcionamuybien
  expiration-milliseconds: 360

management:
      endpoints:
          web:
            exposure:
                include:
                    health,info,metrics

resilience4j.circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      msflujo:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'
resilience4j.retry:
    retryAspectOrder: 2
    instances:
        msflujo:
           maxAttempts: 3
           waitDuration: 5s
resilience4j.timelimiter:
    timeLimiterAspectOrder: 3
    instances:
      msflujo:
        timeout-duration: 3s